import React, { useState } from "react";

const developers = [
  {
    name: "Noushiya A",
   
    bio: "Despite being new to React, Noushi quickly caught up with the team and took charge of the frontend. Her hard work and dedication allowed her to contribute effectively, with Athul refining her work to make it clean and efficient, ensuring the project looks great from all angles..",
    photo: "src/assets/noushi.jpg",
  },
  {
    name: "Adarsh C P",
   
    bio: "Adarsh works closely with Nourin, helping with backend development, and also lends a hand th Athul's work by providing the foundational elements for features. He ensures that everything is in place so the team can build upon it and create something great.",
    photo: "src/assets/adarsh.jpg",
  },
  {
    name: "Nourin Nahan K M",
    
    bio: "As the team lead, Nourin plays a crucial role in handling the backend, keeping everything running efficiently. While she may be quiet, her reliability and ability to get things done make her an indispensable part of the team..",
    photo: "src/assets/nourin.jpg",
  },
  {
    name: "Athul Raj R",
   
    bio: "The idea for the project was generated by Athul, who gave the initial kickstart to the entire endeavor. Constantly gathering suggestions from the team for new featuresh Athul takes charge of developing them into their completed form, ensuring the project stays on track and evolves smoothly..",
    photo: "src/assets/athul.jpg",
  },
];

const DeveloperCard = ({ name, role, bio, photo }) => {
  return (
    <div style={styles.card}>
      <img src={photo} alt={name} style={styles.photo} />
      <h3 style={styles.name}>{name}</h3>
      <p style={styles.role}>{role}</p>
      <p style={styles.bio}>{bio}</p>
    </div>
  );
};

const AboutDevelopers = () => {
  const [showDevelopers, setShowDevelopers] = useState(false);

  return (
    <div style={styles.container}>
      {!showDevelopers ? (
        <div style={styles.introSection}>
          <h1 style={styles.title}>Welcome to lets go </h1>
          <h3 >what is lets go? </h3>
          <p style={styles.introText}>
            confused wherer to go?
          </p>
          <p style={styles.introText}>
            her's the solution . Let's go basically shows all the nearby places that you can visit other than the usual famous spots. 
         
          </p>
          <h3>where does these places comes from ?</h3>
          <p style={styles.introText}>The recommended places you see here are either shared by our amazing users and verified by the admin or handpicked by the admin to showcase stunning, underrated destinations.</p>
         
          <h3>How do users contribute  ?</h3>
          <p style={styles.introText}>
  1. <b>Tap the + Button:</b> It’s at the bottom—hard to miss!  
  <br />
  2. <b>Fill It Out:</b> Add all the details like a pro.  
  <br />
  3. <b>Snap & Upload:</b> Pick a clean, eye-catching photo.  
  <br />
  4. <b>Hit Submit:</b> Boom, you’re done!  
  <br />
  5. <b>Wait for Approval:</b> The admin’s got this.  
  <br />
  6. <b>Ta-da!</b> Your contribution is live for the world to see!  
  <br /><br />
  <i>Remember:</i> People trust your info, so keep it real and responsible. Fix anything off, and let’s keep it awesome!  
</p>

<h3>Campaing ? </h3>
<p style={styles.introText}>Noticed a button called campaing ?</p>
<p style={styles.introText}>
  The purpose it serves is to host restoration campaigns aimed at reviving places damaged by natural disasters or human activities, bringing them back to their prime beauty.
.</p>

<h3>How to host or paticipate in a campaing ?</h3>
<p style={styles.introText}>
Sorry, that page is still under development. I’ll let you know once the developer completes it! </p>
 <button
            style={styles.button}
            onClick={() => setShowDevelopers(true)}
          >
            Meet the Creators
          </button>
        </div>
      ) : (
        <div>
        
          <h2 style={styles.subtitle}>Team: OGS</h2>
          <div style={styles.grid}>
            {developers.map((developer, index) => (
              <DeveloperCard key={index} {...developer} />
            ))}
          </div>
          
        </div>
      )}
    </div>
  );
};

const styles = {
  container: {
    padding: "20px",
    textAlign: "center",
  },
  introSection: {
    marginBottom: "20px",
  },
  title: {
    fontSize: "2.5rem",
    marginBottom: "10px",
  },
  introText: {
    fontSize: "1.2rem",
    marginBottom: "20px",
    color: "#a09e9e",
  },
  button: {
    backgroundColor: "#28a745",
    color: "white",
    border: "none",
    borderRadius: "5px",
    padding: "15px 30px", // Increased padding
    fontSize: "1.2rem",   // Increased font size
    fontWeight: "bold",   // Added bold text
    cursor: "pointer",
    transition: "background-color 0.3s ease, transform 0.2s ease",
    marginTop: "30px",    // Added margin for spacing
    boxShadow: "0 4px 6px rgba(0, 0, 0, 0.2)", // Added shadow for effect
  },
  buttonHover: {
    backgroundColor: "#218838",
    transform: "scale(1.05)", // Button enlarges slightly on hover
  },


  subtitle: {
    fontSize: "1.8rem",
    marginBottom: "20px",
    color: "white ",
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(250px, 1fr))",
    gap: "20px",
  },
  card: {
    backgroundColor: "#f9f9f9",
    borderRadius: "8px",
    boxShadow: "0 4px 6px rgba(0, 0, 0, 0.1)",
    padding: "20px",
    textAlign: "center",
  },
 
    photo: {
      width: "100px",          
      height: "100px",         
      borderRadius: "50%",     
      marginBottom: "15px",    
      objectFit: "cover",
  },
  name: {
    fontSize: "1.5rem",
    margin: "10px 0",
    color: 'grey',
  },
  role: {
    fontSize: "1rem",
    color: "#555",
    margin: "5px 0",
  },
  bio: {
    fontSize: "0.9rem",
    color: "grey",
  },
};

export default AboutDevelopers;
